package com.smartstreamrdu.service.rawdata;

import java.util.Map;
import java.util.Set;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

public abstract class AbstractFeedVsDbRawData implements FeedVsDbRawdataMergeService {
	
	/**
	 * Iterate over feed JSONObject and check each field in DB JSONObject whether it contains.
	 * If input field is not present in db json then input field will be added to DB JSONObject.
	 * If it contains then this will further check for type of input json element.
	 * <ul>
	 * <li>If input field is of type JSONObject then the same method will be called again with the matched field from feed and db json.</li> 
	 * <li>If input field is of type JSONArray then 'matchArrayField' method will be called with the matched field from feed and db json.</li> 
	 * <li>Else, matched input field will overwrite existing db field.</li>
	 * </ul>
	 * 
	 * @param feedFieldsJson
	 * @param dbFieldsJson
	 */
	/**
	 * @param dbObject
	 * @param feedObject
	 */
	@SuppressWarnings("unchecked")
	protected void matchFieldAndMerge(JSONObject feedObject, JSONObject dbObject) {
		Set<Map.Entry<String, Object>> feedFields = feedObject.entrySet();
		for(Map.Entry<String, Object> feedField : feedFields) {
			
			String key = feedField.getKey();
			Object feedValue = feedField.getValue();
			
			if (!dbObject.containsKey(feedField.getKey())) {
				dbObject.put(feedField.getKey(), feedField.getValue());
				continue;
			} 

			if (feedValue instanceof JSONObject) {
				JSONObject value = (JSONObject) feedValue;
				matchFieldAndMerge(value, (JSONObject) dbObject.get(key));
			} else if (feedValue instanceof JSONArray) {
				JSONArray value = (JSONArray) feedValue;
				mergeArrayObject(key, value, dbObject);
			} else {
				dbObject.put(key, feedValue);
			}
		}
	}

	/**
	 * This method is used to merge JSONArray of feed and DB.
	 * Replace the existing element in DB JSONArray with the element(if matches) from feed JSONArray while iterating over feed JSONArray.
	 * Each element from both the arrays are compared on basis of 'key' generated by method 'getArrayObjectKey'.
	 * 
	 * @param arrayTag
	 * @param feedJsonArray
	 * @param dbJsonArray
	 */
	protected abstract void mergeArrayObject(String arrayTag, JSONArray feedValueArray, JSONObject dbObject);
}