/*******************************************************************
 *
 * Copyright (c) 2009-2021 The SmartStream Reference Data Utility 
 * All rights reserved. 
 *
 * File:	FeedVsDbRawdataMergeServiceImpl.java
 * Author:	GMathur
 * Date:	04-Jan-2021
 *
 *******************************************************************
 */
package com.smartstreamrdu.service.rawdata;

import java.util.HashMap;
import java.util.Map;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.springframework.stereotype.Component;

import com.smartstreamrdu.domain.Record;

/**
 * Default implementation for rawdata merge service that will compare feed rawdata to DB rawdata and merge both based on the type of JSON element.
 */
@Component("DefaultFeedVsDbRawdataMergeService")
public class FeedVsDbRawdataMergeServiceImpl extends AbstractFeedVsDbRawData {

	@Override
	public Record merge(Record feedRecord, JSONObject dbRecordJson) {
		JSONObject feedRecordJson = feedRecord.getRecordRawData().getRawData();
		JSONObject modifiedFeedRecordJson = new JSONObject(dbRecordJson);

		matchFieldAndMerge(feedRecordJson, modifiedFeedRecordJson);
		feedRecord.getRecordRawData().setRawData(modifiedFeedRecordJson);
		return feedRecord;
	}

	/**
	 * This method is used to merge JSONArray of feed and DB.
	 * Replace the existing element in DB JSONArray with the element(if matches) from feed JSONArray while iterating over feed JSONArray.
	 * Each element from both the arrays are compared on basis of 'key' generated by method 'getArrayObjectKey'.
	 * 
	 * @param arrayTag
	 * @param feedJsonArray
	 * @param dbJsonArray
	 */
	@SuppressWarnings("unchecked")
	@Override
	protected void mergeArrayObject(String arrayTag, JSONArray feedJsonArray, JSONObject dbJsonObject) {
		JSONArray dbJsonArray = (JSONArray) dbJsonObject.get(arrayTag);
		Map<String, Integer> feedArrayKeyMap = getJsonArrayKeyMap(arrayTag, feedJsonArray);
		Map<String, Integer> dbArrayKeyMap = getJsonArrayKeyMap(arrayTag, dbJsonArray);
		
		feedArrayKeyMap.keySet().forEach(k -> {
			if(dbArrayKeyMap.containsKey(k)) {
				dbJsonArray.remove(dbArrayKeyMap.get(k).intValue());
			}
			dbJsonArray.add(feedArrayKeyMap.get(k));
		});
	}
	
	/**
	 * Return Map<K, V> for input JSONArray.
	 * Key and value for this map are defined as below
	 * K - Unique key for each element of input JSONArray that is generated by method 'getJsonArrayKeyMap'.
	 * V - Index for each element.
	 * 
	 * @param arrayTag
	 * @param inputJsonArray
	 * @return
	 */
	private Map<String, Integer> getJsonArrayKeyMap(String arrayTag, JSONArray inputJsonArray) {
		Map<String, Integer> keyIndexMap = new HashMap<>();
		if(!inputJsonArray.isEmpty()) {
			for(int i=0;i<inputJsonArray.size();i++) {
				keyIndexMap.put(getArrayObjectKey(arrayTag, (JSONObject)inputJsonArray.get(i)), i);
			}
		}
		return keyIndexMap;
	}
	
	@Override
	public String getArrayObjectKey(String arrayTag, JSONObject arrayEntry) {
		throw new UnsupportedOperationException("JSONArray is not expected in rawdata");
	}
}
